### ISSUE TITLE
[Bug] 인지하고 고치고 있는 오류

### ISSUE THREAD

**Issue by jwo1024** [PinTogether/frontend#114]
#### 프로필 수정 페이지
- [x] 수정페이지 들어갔을때 내 현재 닉네임, 사진 안보이는 문제

#### 핀 수정 페이지
- [x] 핀 수정 안됨 & 사진 안올라감

#### 장소 조회 페이지
- [x] api endpoint 오타 
   - ` /places/557523/pins?page=0&size=50}  요청 메서드: GET`
- [ ] 리뷰내용, 사진, 없을때 카드를 어떻게 구성할지?
- [x] 컬렉션 조회 -> 장소더보기 -> 스크롤 아래로 내리면 갑자기 다 핀목록이 사라집니다

#### Card
- [x] PlaceCard 이름 클릭시 장소페이지로 라우팅 되어야함
- [x] ReviewCard 컬렉션 보러가기 클릭시 컬렉션 페이지로 이동

#### 로그인 페이지
- [x] 탈퇴시 auth cookie & localdata myProfile 삭제
- [ ] 탈퇴 api 동작하는 것 맞는지 확인 필요
- [x] fetch 401 반환시 logout 세션 동작

#### 검색 페이지
- [x] 최근 검색 중복되는 string 걸러주기 요청하기

#### 프로필 페이지
- [x] 찜 목록 보기 -> 찜 삭제시 유저에게 삭제된 데이터로 업데이트 안됨

**Comment by UMGGG** [comment]
- 핀 추가하기 에서 핀 추가할때 에러를 뱉는데 핀은 추가되어있는 상태입니다

- 컬렉션 조회 -> 장소더보기 -> 스크롤 아래로 내리면 갑자기 다 핀목록이 사라집니다

**Comment by jwo1024** [comment]
> * 핀 추가하기 에서 핀 추가할때 에러를 뱉는데 핀은 추가되어있는 상태입니다
> * 컬렉션 조회 -> 장소더보기 -> 스크롤 아래로 내리면 갑자기 다 핀목록이 사라집니다

https://github.com/PinTogether/frontend/issues/119#issuecomment-2023369462
