### ISSUE TITLE
[Bug] 찾은 오류, 수정해야하는 오류, 추가 수정사항

### ISSUE THREAD

**Issue by UMGGG** [PinTogether/frontend#119]
### 수정해야할 것
- [x] 마커데이터에서 장소조회에 필요한 Id는 pinId가 아닌 placeId가 필요함
- [x] pin data에서 placeId가 number || undefined이기 때문에 undefined 일 때 필터링에 문제가 생김 -> placeId는 undefined 풀기
- [x] 프로필페이지 버튼 흔들리는거 수정하기
- [x] 프로필 페이지 버튼 클릭시 내 정보가 스크롤바 여부에 따라 위치 바뀜 -> 스크롤바 모양이 표시되지않도록 변경
- [x] 알람 아이콘 notify 페이지와 연결하기
- [x] search 인풋창 클릭시 css 밀림
- [x] overlay 컬렉션 선택으로 마커들을 띄운 상태에서 collection 페이지에 들어가 마커를 초기화 시킨 이후 다시 overlay 컬렉션 선택시 이전의 마커 데이터들이 그대로 남아 같이 생성되는 문제
- [x] 특정 컬렉션의 핀 정보 받아오기 api에서 받아와지는 saveCnt는 장소의 pinCnt와 달라 마커를 생성할 때 필요한  해당 장소의 핀 개수를 하나씩 따로 받아오거나 api에서 pinCnt를 추가로 넘겨주도록 해야함 

### 발견한 것
- [x] 핀 추가하기에서 핀 추가할때 에러를 뱉는데 핀은 추가되어있음
- [x] 컬렉션 조회 -> 장소더보기 -> 스크롤 아래로 내리면 갑자기 다 사라짐
- [x] 한 컬렉션에 중복으로 같은 장소가 들어갈 수 있는게 맞는지? 아니라면 수정해야 함
- [x] 검색에 %톤쇼우 같은 방식으로 검색시 잘못된 결과가 나옴
- ...

### 추가 수정사항
- [x] place조회 페이지에서 장소 이름을 클릭해야만 지도에서 이동되게 변경
- [x] 지도에 마커들이 띄워져 있는 상태에서 하나의 마커만 새롭게 들어오게 될 때 해당 새 마커가 기존 마커에 존재한다면 마커들을 없에지않고 유지한 상태로 시점만 이동해서 보여주도록 변경
- [x] 오버레이의 컬렉션들을 선택한 상태에서 핀에 영향을 주는 페이지로 이동시 선택된 컬렉션들 해제시키기
- [x] 마커 디자인 변경하기
- [x] 로그인 안했을 시 추천 컬렉션이라고 보여주기
- [x] place카드의 가게 이름을 누를시 페이지이동 + 지도에 띄우기 연동
- [x] 새로 만들어주신 homepageCardComponents 메인페이지에 적용하기
- [x] 검색 결과 지도에 마커로 띄우기
- [x] 지도 내 검색기능 추가
- [x] 내 위치 마커 찍기
- [x] 음식점, 카페 찾기 버튼
- [x] 지도 범위 장소 찾기버튼
- [x] 메인페이지 개인정보처리방침 등 표기

**Comment by jwo1024** [comment]
1.  핀 추가하기에서 핀 추가할때 에러를 뱉는데 핀은 추가되어있음
     - backend api  "새 핀 생성" 응답으로 생성된 pin 의 id 정보가 오지 않아 타입에러가 발생하여, pin 생성 실패로 처리되는 에러입니다
    
2.  스크롤 아래로 내리면 갑자기 다 사라짐
     - 마지막 응답으로 빈배열이 오면, 이전에 받아두었던 데이터가 빈배열로 대체되어 나타나는 에러입니다
     - 제 환경에서는 수정해두었으니, 다음 PR 때 같이 올리겠습니다!
